version: "3.7"

services:
  core:
    build: .
    ports:
      - 39797:39797/tcp
      - 39797:39797/udp
    restart: unless-stopped
    secrets:
      - account_address
      - account_password
    volumes:
      - ./volumes/root/.energicore3:/root/.energicore3

secrets:
  account_address:
    file: ./configs/energi3_account_address
  account_password:
    file: ./configs/energi3_account_password
